### ISSUE TITLE
Make mini-tps run with dnf5 only

### ISSUE THREAD

**Issue by jpopelka** [fedora-ci/mini-tps#57]
Due to this
https://github.com/fedora-ci/mini-tps/blob/8a17ce8a8cab4d7b74cd10370e9dbef9bb977f3e/mtps-setup#L46-L47
if there are `dnf5` and `dnf-3` installed mini-tps decides to use the `dnf-3`.

The code was added in #25 (don't expect any explanation in the PR or the commit :) )
and I think the reason for falling back to dnf-3 is that back then the dnf5 was still "not production ready".
I think we should remove it and use dnf5 if it's installed.

**Comment by LecrisUT** [comment]
It seems rawhide is starting to be affected by this:
- https://matrix.to/#/!DMptnKvPTdgoULzUTV:fedoraproject.org/$B8K-Qn4_jBZFPTRa7H6B2c4UDT4Jw2cmeVYIMc0NAOk?via=fedoraproject.org&via=fedora.im&via=matrix.org
- https://artifacts.dev.testing-farm.io/2d9fe3ec-821f-4ba6-ba80-0d393b6475dc/

**Comment by jpopelka** [comment]
Done in #55
